In [1]:
import tensorflow as tf
print(f"Gpus disponibles : {tf.config.list_physical_devices('GPU')}")

Gpus disponibles : []


In [2]:
import tensorflow as tf
import numpy as np 

print(f"Version de Tensorflow {tf.__version__}")

Version de Tensorflow 2.18.0


In [3]:
a = np.array([1, 2, 4])
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(f"Tensor t_a : {t_a}")
print(f"Tensor t_a : {t_b}")

Tensor t_a : [1 2 4]
Tensor t_a : [4 5 6]


In [4]:
print(f"Es 'a' un tensor {tf.is_tensor(a)}")
print(f"Es 't_a' un tensor {tf.is_tensor(t_a)}")

Es 'a' un tensor False
Es 't_a' un tensor True


In [5]:
t_ones = tf.ones((2, 3))
print(f"Tensor de unos {t_ones}")

print(f"Tensor de unos array de Numpy {t_ones.numpy()}")

Tensor de unos [[1. 1. 1.]
 [1. 1. 1.]]
Tensor de unos array de Numpy [[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
conts_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(f"Tensor contante {conts_tensor}")


Tensor contante [1.2       5.        3.1415927]


In [7]:
tensor_lleno = tf.fill((2, 3),1)
print(f"Tensor lleno de unos {tensor_lleno}")

Tensor lleno de unos [[1 1 1]
 [1 1 1]]


In [8]:
one_hot_tensor = tf.one_hot([0, 1, 2], 4)
print(f"Tensor one-hot {one_hot_tensor}")

Tensor one-hot [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [9]:
t_a_new = tf.cast(t_a, tf.int64)
print(f"Nuevo tipo de dato t_a_new : {t_a_new}")

Nuevo tipo de dato t_a_new : [1 2 4]


In [10]:
t = tf.random.uniform(shape=(3,5))
t_tr = tf.transpose(t)
print(f"Forma origina {t.shape} ---> Forma transpuesta {t_tr.shape}")

Forma origina (3, 5) ---> Forma transpuesta (5, 3)


In [11]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5,6))
print(f"Nueva forma del tensor: {t_reshape.shape}")

Nueva forma del tensor: (5, 6)


In [12]:
t = tf.zeros((1,2,1,4,1))
t_sqz = tf.squeeze(t, axis=(2,4))
print(f"Forma original {t.shape} ----> Forma Comprimida {t_sqz.shape}")

Forma original (1, 2, 1, 4, 1) ----> Forma Comprimida (1, 2, 4)


In [13]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5,2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5,2), mean=0.0, stddev=1.0)

t3 = tf.multiply(t1, t2).numpy()
print(f"Resultado de la multiplicacion {t3}")

Resultado de la multiplicacion [[-0.26996338 -0.87363994]
 [-0.01652772 -0.17496566]
 [-0.296179   -0.13944866]
 [-0.7272108   0.13463594]
 [-0.40087393  0.00445268]]


In [14]:
t4 = tf.math.reduce_mean(t1, axis=0)
print(f"{t4}")

[0.08957257 0.2074099 ]


In [15]:
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print(f"Resultado de la multiplicacion de matrices {t5.numpy()}")

Resultado de la multiplicacion de matrices [[-1.1436033   1.1154624  -0.8695717  -0.3210435   0.8555103 ]
 [ 0.2480186  -0.19149339  0.2504958  -0.0644026  -0.3307204 ]
 [-0.47782415  0.40717956 -0.43562764  0.02238911  0.5270062 ]
 [ 0.52479297 -0.23352614  0.74080014 -0.5925749  -1.1940588 ]
 [-0.09918742  0.26019508  0.12526006 -0.46231267 -0.39642125]]


In [ ]:
# t = tf.random.uniform()

TypeError: Missing required positional argument

In [ ]:
A = tf.ones((3,))
B = tf.zeros((2,))

C = tf.concat([A, B], axis=0)
print(f"Tensor concatenado {C.numpy()}")

Tensor concatenado [1. 1. 1. 0. 0.]


In [ ]:
A = tf.ones((3, ))
B = tf.zeros((3, ))

S = tf.stack([A, B], axis=1)
print("Tensor apilado: ", S.numpy())